name: Schild
author: Justin_SGD
version: 3.3
main: de.schild.SchildMain
commands:
  schild:
    description: Edit a sign.
  reloadschild:
    description: Reload the config.
    aliases: [schildreload, reloadconfig]